### View all staff (Only admin)
GET http://localhost:3000/auth/staff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhZG1pbjAxIiwidXNlcm5hbWUiOiJyb2xseSIsIm5hbWUiOiJPcm9ib2xhIFJvbGFuZCBPZ3VuZGlwZSIsImlhdCI6MTY4NjkyMDA5MywiZXhwIjoxNjg2OTIwMjEzfQ.iiCkCHu7LzY6Uz7rn0pbS01ysXPNOhmRV1G8bTLM3pM


### loginAdmin
POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
    "username": "rolly",
    "password": "12345"
}


### LogoutAdmin
POST http://localhost:3000/logoutAdmin
Content-Type: application/json