### View all staff (Only admin)
GET http://localhost:3000/auth/staff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJhZG1pbjAxIiwidXNlcm5hbWUiOiJyb2xseSIsIm5hbWUiOiJPcm9ib2xhIFJvbGFuZCBPZ3VuZGlwZSIsImlhdCI6MTY4NjkyMDA5MywiZXhwIjoxNjg2OTIwMjEzfQ.iiCkCHu7LzY6Uz7rn0pbS01ysXPNOhmRV1G8bTLM3pM


### grantLoginAccessToAdmin
POST http://localhost:3000/grant-admin-access
Content-Type: application/json

{
    "accessCode": "xaBOX251n"
}

### loginAdmin
POST http://localhost:3000/loginAdmin
Content-Type: application/json

{
    "username": "rolly",
    "password": "12345b"
}


### LogoutAdmin
POST http://localhost:3000/logoutAdmin
Content-Type: application/json


### createStaffUser
POST http://localhost:3000/auth/register-staff
Content-Type: application/json

{
    "firstname": "jj",
    "middlename": "jj",
    "lastname": "jj",
    "phoneno": "4788755344",
    "role": "FA"
}


### deleteStaff
DELETE http://localhost:3000/auth/staff/64a321309b40291d5f7debb2
Content-Type: application/json



### Homepage
GET http://localhost:3000/
Content-Type: application/json


### Non existing page
GET http://localhost:3000/jshs
Content-Type: application/json